// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxPAbWfyKwIaRm5KrOJopig8SWPEqted8',
    appId: '1:992918306136:web:037a57470833c368b0792d',
    messagingSenderId: '992918306136',
    projectId: 'top-tier-9814f',
    authDomain: 'top-tier-9814f.firebaseapp.com',
    storageBucket: 'top-tier-9814f.appspot.com',
    measurementId: 'G-2LCBC61VM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6cgBKuug0QKxt_R-noYZWdNz_IxqgB0M',
    appId: '1:992918306136:android:f112912707434d58b0792d',
    messagingSenderId: '992918306136',
    projectId: 'top-tier-9814f',
    storageBucket: 'top-tier-9814f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunynEQczbDHghqa-rPL56DYcCc9snd74',
    appId: '1:992918306136:ios:3a71431a1d719dc2b0792d',
    messagingSenderId: '992918306136',
    projectId: 'top-tier-9814f',
    storageBucket: 'top-tier-9814f.appspot.com',
    iosBundleId: 'com.example.TopTier.projectPinkPantherCitex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunynEQczbDHghqa-rPL56DYcCc9snd74',
    appId: '1:992918306136:ios:12edeca198ae42ceb0792d',
    messagingSenderId: '992918306136',
    projectId: 'top-tier-9814f',
    storageBucket: 'top-tier-9814f.appspot.com',
    iosBundleId: '1',
  );
}
